services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_USER: vincent
      MARIADB_PASSWORD: larochette
      MARIADB_DATABASE: vente
      MARIADB_ROOT_PASSWORD: toto
    ports:
      - 3306:3306
  monapache:
    image: larochev/monapache
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
  monubuntu:
    image: larochev/monubuntu
  phpmyadmin: 
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
